// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as ConnectionPingProcedure from "../connection_ping_procedure";

export type ConnectionPingArgs = __Infer<typeof ConnectionPingProcedure.params>;
export type ConnectionPingResult = __Infer<typeof ConnectionPingProcedure.returnType>;

