// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AuthorizeOtaPublisherReducer from "../authorize_ota_publisher_reducer";
import LinkAccountReducer from "../link_account_reducer";
import PromoteOtaChannelReducer from "../promote_ota_channel_reducer";
import PublishOtaReleaseReducer from "../publish_ota_release_reducer";
import RegisterAccountReducer from "../register_account_reducer";
import SetAccountDisplayNameReducer from "../set_account_display_name_reducer";
import SetAccountEmailReducer from "../set_account_email_reducer";

export type AuthorizeOtaPublisherParams = __Infer<typeof AuthorizeOtaPublisherReducer>;
export type LinkAccountParams = __Infer<typeof LinkAccountReducer>;
export type PromoteOtaChannelParams = __Infer<typeof PromoteOtaChannelReducer>;
export type PublishOtaReleaseParams = __Infer<typeof PublishOtaReleaseReducer>;
export type RegisterAccountParams = __Infer<typeof RegisterAccountReducer>;
export type SetAccountDisplayNameParams = __Infer<typeof SetAccountDisplayNameReducer>;
export type SetAccountEmailParams = __Infer<typeof SetAccountEmailReducer>;

