// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountDetails {
    pub id: String,
    pub public_key: Vec<u8>,
    pub revision: u64,
    pub email: String,
    pub display_name: String,
}

impl __sdk::InModule for AccountDetails {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountDetails`.
///
/// Provides typed access to columns for query building.
pub struct AccountDetailsCols {
    pub id: __sdk::__query_builder::Col<AccountDetails, String>,
    pub public_key: __sdk::__query_builder::Col<AccountDetails, Vec<u8>>,
    pub revision: __sdk::__query_builder::Col<AccountDetails, u64>,
    pub email: __sdk::__query_builder::Col<AccountDetails, String>,
    pub display_name: __sdk::__query_builder::Col<AccountDetails, String>,
}

impl __sdk::__query_builder::HasCols for AccountDetails {
    type Cols = AccountDetailsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountDetailsCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            public_key: __sdk::__query_builder::Col::new(table_name, "public_key"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
        }
    }
}
