// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_type::Account;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `account`.
///
/// Obtain a handle from the [`AccountTableAccess::account`] method on [`super::RemoteTables`],
/// like `ctx.db.account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account().on_insert(...)`.
pub struct AccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<Account>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `account`.
pub struct AccountTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AccountTableAccessor {
    type Row = Account;
    type Handle<'db> = AccountTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.account()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AccountTableHandle`], which mediates access to the table `account`.
    fn account(&self) -> AccountTableHandle<'_>;
}

impl AccountTableAccess for super::RemoteTables {
    fn account(&self) -> AccountTableHandle<'_> {
        AccountTableHandle {
            imp: self.imp.get_table::<Account>("account"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AccountInsertCallbackId(__sdk::CallbackId);
pub struct AccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AccountTableHandle<'ctx> {
    type Row = Account;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Account> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AccountTableHandle<'ctx> {
    type Row = Account;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Account> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountInsertCallbackId {
        AccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountDeleteCallbackId {
        AccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AccountTableHandle<'ctx> {
    type InsertCallbackId = AccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountInsertCallbackId {
        AccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AccountTableHandle<'ctx> {
    type DeleteCallbackId = AccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountDeleteCallbackId {
        AccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AccountTableHandle<'ctx> {
    type UpdateCallbackId = AccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountUpdateCallbackId {
        AccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AccountTableHandle<'ctx> {
    type UpdateCallbackId = AccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountUpdateCallbackId {
        AccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `account`,
/// which allows point queries on the field of the same name
/// via the [`AccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account().id().find(...)`.
pub struct AccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Account, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AccountTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `account`.
    pub fn id(&self) -> AccountIdUnique<'ctx> {
        AccountIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AccountIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Account> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Account>("account");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Account>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Account>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Account`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait accountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Account`.
    fn account(&self) -> __sdk::__query_builder::Table<Account>;
}

impl accountQueryTableAccess for __sdk::QueryTableAccessor {
    fn account(&self) -> __sdk::__query_builder::Table<Account> {
        __sdk::__query_builder::Table::new("account")
    }
}
