// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountEmail {
    pub account_id: String,
    pub email: String,
}

impl __sdk::InModule for AccountEmail {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountEmail`.
///
/// Provides typed access to columns for query building.
pub struct AccountEmailCols {
    pub account_id: __sdk::__query_builder::Col<AccountEmail, String>,
    pub email: __sdk::__query_builder::Col<AccountEmail, String>,
}

impl __sdk::__query_builder::HasCols for AccountEmail {
    type Cols = AccountEmailCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountEmailCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountEmail`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountEmailIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AccountEmail, String>,
}

impl __sdk::__query_builder::HasIxCols for AccountEmail {
    type IxCols = AccountEmailIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountEmailIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountEmail {}
