// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountBinding {
    pub sender: __sdk::Identity,
    pub account_id: String,
}

impl __sdk::InModule for AccountBinding {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountBinding`.
///
/// Provides typed access to columns for query building.
pub struct AccountBindingCols {
    pub sender: __sdk::__query_builder::Col<AccountBinding, __sdk::Identity>,
    pub account_id: __sdk::__query_builder::Col<AccountBinding, String>,
}

impl __sdk::__query_builder::HasCols for AccountBinding {
    type Cols = AccountBindingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountBindingCols {
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
        }
    }
}

/// Indexed column accessor struct for the table `AccountBinding`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountBindingIxCols {
    pub sender: __sdk::__query_builder::IxCol<AccountBinding, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AccountBinding {
    type IxCols = AccountBindingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountBindingIxCols {
            sender: __sdk::__query_builder::IxCol::new(table_name, "sender"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountBinding {}
