// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AuthorizeOtaPublisherArgs {
    pub identity: String,
    pub authorized: bool,
}

impl From<AuthorizeOtaPublisherArgs> for super::Reducer {
    fn from(args: AuthorizeOtaPublisherArgs) -> Self {
        Self::AuthorizeOtaPublisher {
            identity: args.identity,
            authorized: args.authorized,
        }
    }
}

impl __sdk::InModule for AuthorizeOtaPublisherArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `authorize_ota_publisher`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait authorize_ota_publisher {
    /// Request that the remote module invoke the reducer `authorize_ota_publisher` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`authorize_ota_publisher:authorize_ota_publisher_then`] to run a callback after the reducer completes.
    fn authorize_ota_publisher(&self, identity: String, authorized: bool) -> __sdk::Result<()> {
        self.authorize_ota_publisher_then(identity, authorized, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `authorize_ota_publisher` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn authorize_ota_publisher_then(
        &self,
        identity: String,
        authorized: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl authorize_ota_publisher for super::RemoteReducers {
    fn authorize_ota_publisher_then(
        &self,
        identity: String,
        authorized: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AuthorizeOtaPublisherArgs {
                identity,
                authorized,
            },
            callback,
        )
    }
}
