// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ConnectionPingArgs {
    pub nonce: u64,
}

impl __sdk::InModule for ConnectionPingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `connection_ping`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait connection_ping {
    fn connection_ping(&self, nonce: u64) {
        self.connection_ping_then(nonce, |_, _| {});
    }

    fn connection_ping_then(
        &self,
        nonce: u64,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<u64, __sdk::InternalError>)
        + Send
        + 'static,
    );
}

impl connection_ping for super::RemoteProcedures {
    fn connection_ping_then(
        &self,
        nonce: u64,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<u64, __sdk::InternalError>)
        + Send
        + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, u64>(
            "connection_ping",
            ConnectionPingArgs { nonce },
            __callback,
        );
    }
}
