// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LinkAccountArgs {
    pub proof: Vec<u8>,
}

impl From<LinkAccountArgs> for super::Reducer {
    fn from(args: LinkAccountArgs) -> Self {
        Self::LinkAccount { proof: args.proof }
    }
}

impl __sdk::InModule for LinkAccountArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `link_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait link_account {
    /// Request that the remote module invoke the reducer `link_account` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`link_account:link_account_then`] to run a callback after the reducer completes.
    fn link_account(&self, proof: Vec<u8>) -> __sdk::Result<()> {
        self.link_account_then(proof, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `link_account` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn link_account_then(
        &self,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl link_account for super::RemoteReducers {
    fn link_account_then(
        &self,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(LinkAccountArgs { proof }, callback)
    }
}
