// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_details_type::AccountDetails;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_account`.
///
/// Obtain a handle from the [`MyAccountTableAccess::my_account`] method on [`super::RemoteTables`],
/// like `ctx.db.my_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_account().on_insert(...)`.
pub struct MyAccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountDetails>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_account`.
pub struct MyAccountTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyAccountTableAccessor {
    type Row = AccountDetails;
    type Handle<'db> = MyAccountTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_account()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAccountTableHandle`], which mediates access to the table `my_account`.
    fn my_account(&self) -> MyAccountTableHandle<'_>;
}

impl MyAccountTableAccess for super::RemoteTables {
    fn my_account(&self) -> MyAccountTableHandle<'_> {
        MyAccountTableHandle {
            imp: self.imp.get_table::<AccountDetails>("my_account"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAccountInsertCallbackId(__sdk::CallbackId);
pub struct MyAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyAccountTableHandle<'ctx> {
    type Row = AccountDetails;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountDetails> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyAccountTableHandle<'ctx> {
    type Row = AccountDetails;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountDetails> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountInsertCallbackId {
        MyAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountDeleteCallbackId {
        MyAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyAccountTableHandle<'ctx> {
    type InsertCallbackId = MyAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountInsertCallbackId {
        MyAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyAccountTableHandle<'ctx> {
    type DeleteCallbackId = MyAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAccountDeleteCallbackId {
        MyAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountDetails>("my_account");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountDetails>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountDetails>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountDetails`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_accountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountDetails`.
    fn my_account(&self) -> __sdk::__query_builder::Table<AccountDetails>;
}

impl my_accountQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_account(&self) -> __sdk::__query_builder::Table<AccountDetails> {
        __sdk::__query_builder::Table::new("my_account")
    }
}
