// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ota_release_type::OtaRelease;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ota_release`.
///
/// Obtain a handle from the [`OtaReleaseTableAccess::ota_release`] method on [`super::RemoteTables`],
/// like `ctx.db.ota_release()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ota_release().on_insert(...)`.
pub struct OtaReleaseTableHandle<'ctx> {
    imp: __sdk::TableHandle<OtaRelease>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ota_release`.
pub struct OtaReleaseTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for OtaReleaseTableAccessor {
    type Row = OtaRelease;
    type Handle<'db> = OtaReleaseTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ota_release()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ota_release`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OtaReleaseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OtaReleaseTableHandle`], which mediates access to the table `ota_release`.
    fn ota_release(&self) -> OtaReleaseTableHandle<'_>;
}

impl OtaReleaseTableAccess for super::RemoteTables {
    fn ota_release(&self) -> OtaReleaseTableHandle<'_> {
        OtaReleaseTableHandle {
            imp: self.imp.get_table::<OtaRelease>("ota_release"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OtaReleaseInsertCallbackId(__sdk::CallbackId);
pub struct OtaReleaseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for OtaReleaseTableHandle<'ctx> {
    type Row = OtaRelease;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OtaRelease> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for OtaReleaseTableHandle<'ctx> {
    type Row = OtaRelease;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OtaRelease> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OtaReleaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaReleaseInsertCallbackId {
        OtaReleaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OtaReleaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OtaReleaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaReleaseDeleteCallbackId {
        OtaReleaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OtaReleaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for OtaReleaseTableHandle<'ctx> {
    type InsertCallbackId = OtaReleaseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaReleaseInsertCallbackId {
        OtaReleaseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OtaReleaseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for OtaReleaseTableHandle<'ctx> {
    type DeleteCallbackId = OtaReleaseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaReleaseDeleteCallbackId {
        OtaReleaseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OtaReleaseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OtaReleaseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OtaReleaseTableHandle<'ctx> {
    type UpdateCallbackId = OtaReleaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OtaReleaseUpdateCallbackId {
        OtaReleaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OtaReleaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for OtaReleaseTableHandle<'ctx> {
    type UpdateCallbackId = OtaReleaseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OtaReleaseUpdateCallbackId {
        OtaReleaseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OtaReleaseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `release_id` unique index on the table `ota_release`,
/// which allows point queries on the field of the same name
/// via the [`OtaReleaseReleaseIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ota_release().release_id().find(...)`.
pub struct OtaReleaseReleaseIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<OtaRelease, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OtaReleaseTableHandle<'ctx> {
    /// Get a handle on the `release_id` unique index on the table `ota_release`.
    pub fn release_id(&self) -> OtaReleaseReleaseIdUnique<'ctx> {
        OtaReleaseReleaseIdUnique {
            imp: self.imp.get_unique_constraint::<String>("release_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OtaReleaseReleaseIdUnique<'ctx> {
    /// Find the subscribed row whose `release_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<OtaRelease> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OtaRelease>("ota_release");
    _table.add_unique_constraint::<String>("release_id", |row| &row.release_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OtaRelease>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OtaRelease>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OtaRelease`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ota_releaseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OtaRelease`.
    fn ota_release(&self) -> __sdk::__query_builder::Table<OtaRelease>;
}

impl ota_releaseQueryTableAccess for __sdk::QueryTableAccessor {
    fn ota_release(&self) -> __sdk::__query_builder::Table<OtaRelease> {
        __sdk::__query_builder::Table::new("ota_release")
    }
}
