// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OtaPublisher {
    pub identity: __sdk::Identity,
}

impl __sdk::InModule for OtaPublisher {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OtaPublisher`.
///
/// Provides typed access to columns for query building.
pub struct OtaPublisherCols {
    pub identity: __sdk::__query_builder::Col<OtaPublisher, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for OtaPublisher {
    type Cols = OtaPublisherCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OtaPublisherCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
        }
    }
}

/// Indexed column accessor struct for the table `OtaPublisher`.
///
/// Provides typed access to indexed columns for query building.
pub struct OtaPublisherIxCols {
    pub identity: __sdk::__query_builder::IxCol<OtaPublisher, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for OtaPublisher {
    type IxCols = OtaPublisherIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OtaPublisherIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OtaPublisher {}
