// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OtaAuthority {
    pub id: u8,
    pub owner: __sdk::Identity,
}

impl __sdk::InModule for OtaAuthority {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OtaAuthority`.
///
/// Provides typed access to columns for query building.
pub struct OtaAuthorityCols {
    pub id: __sdk::__query_builder::Col<OtaAuthority, u8>,
    pub owner: __sdk::__query_builder::Col<OtaAuthority, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for OtaAuthority {
    type Cols = OtaAuthorityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OtaAuthorityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `OtaAuthority`.
///
/// Provides typed access to indexed columns for query building.
pub struct OtaAuthorityIxCols {
    pub id: __sdk::__query_builder::IxCol<OtaAuthority, u8>,
}

impl __sdk::__query_builder::HasIxCols for OtaAuthority {
    type IxCols = OtaAuthorityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OtaAuthorityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OtaAuthority {}
