// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ota_channel_type::OtaChannel;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ota_channel`.
///
/// Obtain a handle from the [`OtaChannelTableAccess::ota_channel`] method on [`super::RemoteTables`],
/// like `ctx.db.ota_channel()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ota_channel().on_insert(...)`.
pub struct OtaChannelTableHandle<'ctx> {
    imp: __sdk::TableHandle<OtaChannel>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `ota_channel`.
pub struct OtaChannelTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for OtaChannelTableAccessor {
    type Row = OtaChannel;
    type Handle<'db> = OtaChannelTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.ota_channel()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ota_channel`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OtaChannelTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OtaChannelTableHandle`], which mediates access to the table `ota_channel`.
    fn ota_channel(&self) -> OtaChannelTableHandle<'_>;
}

impl OtaChannelTableAccess for super::RemoteTables {
    fn ota_channel(&self) -> OtaChannelTableHandle<'_> {
        OtaChannelTableHandle {
            imp: self.imp.get_table::<OtaChannel>("ota_channel"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OtaChannelInsertCallbackId(__sdk::CallbackId);
pub struct OtaChannelDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for OtaChannelTableHandle<'ctx> {
    type Row = OtaChannel;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OtaChannel> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for OtaChannelTableHandle<'ctx> {
    type Row = OtaChannel;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OtaChannel> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OtaChannelInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaChannelInsertCallbackId {
        OtaChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OtaChannelInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OtaChannelDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaChannelDeleteCallbackId {
        OtaChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OtaChannelDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for OtaChannelTableHandle<'ctx> {
    type InsertCallbackId = OtaChannelInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaChannelInsertCallbackId {
        OtaChannelInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OtaChannelInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for OtaChannelTableHandle<'ctx> {
    type DeleteCallbackId = OtaChannelDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OtaChannelDeleteCallbackId {
        OtaChannelDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OtaChannelDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OtaChannelUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OtaChannelTableHandle<'ctx> {
    type UpdateCallbackId = OtaChannelUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OtaChannelUpdateCallbackId {
        OtaChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OtaChannelUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for OtaChannelTableHandle<'ctx> {
    type UpdateCallbackId = OtaChannelUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OtaChannelUpdateCallbackId {
        OtaChannelUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OtaChannelUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `channel` unique index on the table `ota_channel`,
/// which allows point queries on the field of the same name
/// via the [`OtaChannelChannelUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ota_channel().channel().find(...)`.
pub struct OtaChannelChannelUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<OtaChannel, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OtaChannelTableHandle<'ctx> {
    /// Get a handle on the `channel` unique index on the table `ota_channel`.
    pub fn channel(&self) -> OtaChannelChannelUnique<'ctx> {
        OtaChannelChannelUnique {
            imp: self.imp.get_unique_constraint::<String>("channel"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OtaChannelChannelUnique<'ctx> {
    /// Find the subscribed row whose `channel` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<OtaChannel> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<OtaChannel>("ota_channel");
    _table.add_unique_constraint::<String>("channel", |row| &row.channel);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<OtaChannel>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<OtaChannel>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `OtaChannel`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ota_channelQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `OtaChannel`.
    fn ota_channel(&self) -> __sdk::__query_builder::Table<OtaChannel>;
}

impl ota_channelQueryTableAccess for __sdk::QueryTableAccessor {
    fn ota_channel(&self) -> __sdk::__query_builder::Table<OtaChannel> {
        __sdk::__query_builder::Table::new("ota_channel")
    }
}
