// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OtaRelease {
    pub release_id: String,
    pub manifest_json: String,
    pub manifest_sha_256: String,
    pub release_base_url: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for OtaRelease {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OtaRelease`.
///
/// Provides typed access to columns for query building.
pub struct OtaReleaseCols {
    pub release_id: __sdk::__query_builder::Col<OtaRelease, String>,
    pub manifest_json: __sdk::__query_builder::Col<OtaRelease, String>,
    pub manifest_sha_256: __sdk::__query_builder::Col<OtaRelease, String>,
    pub release_base_url: __sdk::__query_builder::Col<OtaRelease, String>,
    pub created_at: __sdk::__query_builder::Col<OtaRelease, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for OtaRelease {
    type Cols = OtaReleaseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OtaReleaseCols {
            release_id: __sdk::__query_builder::Col::new(table_name, "release_id"),
            manifest_json: __sdk::__query_builder::Col::new(table_name, "manifest_json"),
            manifest_sha_256: __sdk::__query_builder::Col::new(table_name, "manifest_sha_256"),
            release_base_url: __sdk::__query_builder::Col::new(table_name, "release_base_url"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OtaRelease`.
///
/// Provides typed access to indexed columns for query building.
pub struct OtaReleaseIxCols {
    pub release_id: __sdk::__query_builder::IxCol<OtaRelease, String>,
}

impl __sdk::__query_builder::HasIxCols for OtaRelease {
    type IxCols = OtaReleaseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OtaReleaseIxCols {
            release_id: __sdk::__query_builder::IxCol::new(table_name, "release_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OtaRelease {}
