// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct OtaChannel {
    pub channel: String,
    pub release_id: String,
    pub generation: u64,
    pub previous_release_id: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for OtaChannel {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `OtaChannel`.
///
/// Provides typed access to columns for query building.
pub struct OtaChannelCols {
    pub channel: __sdk::__query_builder::Col<OtaChannel, String>,
    pub release_id: __sdk::__query_builder::Col<OtaChannel, String>,
    pub generation: __sdk::__query_builder::Col<OtaChannel, u64>,
    pub previous_release_id: __sdk::__query_builder::Col<OtaChannel, String>,
    pub updated_at: __sdk::__query_builder::Col<OtaChannel, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for OtaChannel {
    type Cols = OtaChannelCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        OtaChannelCols {
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            release_id: __sdk::__query_builder::Col::new(table_name, "release_id"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            previous_release_id: __sdk::__query_builder::Col::new(
                table_name,
                "previous_release_id",
            ),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `OtaChannel`.
///
/// Provides typed access to indexed columns for query building.
pub struct OtaChannelIxCols {
    pub channel: __sdk::__query_builder::IxCol<OtaChannel, String>,
}

impl __sdk::__query_builder::HasIxCols for OtaChannel {
    type IxCols = OtaChannelIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        OtaChannelIxCols {
            channel: __sdk::__query_builder::IxCol::new(table_name, "channel"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for OtaChannel {}
