// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PromoteOtaChannelArgs {
    pub channel: String,
    pub release_id: String,
    pub expected_generation: u64,
}

impl From<PromoteOtaChannelArgs> for super::Reducer {
    fn from(args: PromoteOtaChannelArgs) -> Self {
        Self::PromoteOtaChannel {
            channel: args.channel,
            release_id: args.release_id,
            expected_generation: args.expected_generation,
        }
    }
}

impl __sdk::InModule for PromoteOtaChannelArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `promote_ota_channel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait promote_ota_channel {
    /// Request that the remote module invoke the reducer `promote_ota_channel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`promote_ota_channel:promote_ota_channel_then`] to run a callback after the reducer completes.
    fn promote_ota_channel(
        &self,
        channel: String,
        release_id: String,
        expected_generation: u64,
    ) -> __sdk::Result<()> {
        self.promote_ota_channel_then(channel, release_id, expected_generation, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `promote_ota_channel` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn promote_ota_channel_then(
        &self,
        channel: String,
        release_id: String,
        expected_generation: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl promote_ota_channel for super::RemoteReducers {
    fn promote_ota_channel_then(
        &self,
        channel: String,
        release_id: String,
        expected_generation: u64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PromoteOtaChannelArgs {
                channel,
                release_id,
                expected_generation,
            },
            callback,
        )
    }
}
