// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishOtaReleaseArgs {
    pub release_id: String,
    pub manifest_json: String,
    pub manifest_sha_256: String,
    pub release_base_url: String,
}

impl From<PublishOtaReleaseArgs> for super::Reducer {
    fn from(args: PublishOtaReleaseArgs) -> Self {
        Self::PublishOtaRelease {
            release_id: args.release_id,
            manifest_json: args.manifest_json,
            manifest_sha_256: args.manifest_sha_256,
            release_base_url: args.release_base_url,
        }
    }
}

impl __sdk::InModule for PublishOtaReleaseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_ota_release`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_ota_release {
    /// Request that the remote module invoke the reducer `publish_ota_release` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_ota_release:publish_ota_release_then`] to run a callback after the reducer completes.
    fn publish_ota_release(
        &self,
        release_id: String,
        manifest_json: String,
        manifest_sha_256: String,
        release_base_url: String,
    ) -> __sdk::Result<()> {
        self.publish_ota_release_then(
            release_id,
            manifest_json,
            manifest_sha_256,
            release_base_url,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `publish_ota_release` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_ota_release_then(
        &self,
        release_id: String,
        manifest_json: String,
        manifest_sha_256: String,
        release_base_url: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_ota_release for super::RemoteReducers {
    fn publish_ota_release_then(
        &self,
        release_id: String,
        manifest_json: String,
        manifest_sha_256: String,
        release_base_url: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishOtaReleaseArgs {
                release_id,
                manifest_json,
                manifest_sha_256,
                release_base_url,
            },
            callback,
        )
    }
}
