// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAccountDisplayNameArgs {
    pub display_name: String,
    pub proof: Vec<u8>,
}

impl From<SetAccountDisplayNameArgs> for super::Reducer {
    fn from(args: SetAccountDisplayNameArgs) -> Self {
        Self::SetAccountDisplayName {
            display_name: args.display_name,
            proof: args.proof,
        }
    }
}

impl __sdk::InModule for SetAccountDisplayNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_account_display_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_account_display_name {
    /// Request that the remote module invoke the reducer `set_account_display_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_account_display_name:set_account_display_name_then`] to run a callback after the reducer completes.
    fn set_account_display_name(&self, display_name: String, proof: Vec<u8>) -> __sdk::Result<()> {
        self.set_account_display_name_then(display_name, proof, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_account_display_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_account_display_name_then(
        &self,
        display_name: String,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_account_display_name for super::RemoteReducers {
    fn set_account_display_name_then(
        &self,
        display_name: String,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetAccountDisplayNameArgs {
                display_name,
                proof,
            },
            callback,
        )
    }
}
