// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAccountEmailArgs {
    pub email: String,
    pub proof: Vec<u8>,
}

impl From<SetAccountEmailArgs> for super::Reducer {
    fn from(args: SetAccountEmailArgs) -> Self {
        Self::SetAccountEmail {
            email: args.email,
            proof: args.proof,
        }
    }
}

impl __sdk::InModule for SetAccountEmailArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_account_email`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_account_email {
    /// Request that the remote module invoke the reducer `set_account_email` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_account_email:set_account_email_then`] to run a callback after the reducer completes.
    fn set_account_email(&self, email: String, proof: Vec<u8>) -> __sdk::Result<()> {
        self.set_account_email_then(email, proof, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_account_email` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_account_email_then(
        &self,
        email: String,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_account_email for super::RemoteReducers {
    fn set_account_email_then(
        &self,
        email: String,
        proof: Vec<u8>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetAccountEmailArgs { email, proof }, callback)
    }
}
