// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
)

func (v *Account) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.ID)
	bsatn.WriteByteArray(w, v.PublicKey)
	w.PutU64(v.Revision)
	w.PutString(v.DisplayName)
}

func ReadAccount(r bsatn.Reader) (*Account, error) {
	v := &Account{}
	var err error
	v.ID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.PublicKey, err = bsatn.ReadByteArray(r)
	if err != nil {
		return nil, err
	}
	v.Revision, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.DisplayName, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *OtaRelease) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.ReleaseID)
	w.PutString(v.ManifestJSON)
	w.PutString(v.ManifestSha256)
	w.PutString(v.ReleaseBaseURL)
	v.CreatedAt.WriteBsatn(w)
}

func ReadOtaRelease(r bsatn.Reader) (*OtaRelease, error) {
	v := &OtaRelease{}
	var err error
	v.ReleaseID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.ManifestJSON, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.ManifestSha256, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.ReleaseBaseURL, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.CreatedAt, err = types.ReadTimestamp(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *OtaAuthority) WriteBsatn(w bsatn.Writer) {
	w.PutU8(v.ID)
	v.Owner.WriteBsatn(w)
}

func ReadOtaAuthority(r bsatn.Reader) (*OtaAuthority, error) {
	v := &OtaAuthority{}
	var err error
	v.ID, err = r.GetU8()
	if err != nil {
		return nil, err
	}
	v.Owner, err = types.ReadIdentity(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *OtaChannel) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.Channel)
	w.PutString(v.ReleaseID)
	w.PutU64(v.Generation)
	w.PutString(v.PreviousReleaseID)
	v.UpdatedAt.WriteBsatn(w)
}

func ReadOtaChannel(r bsatn.Reader) (*OtaChannel, error) {
	v := &OtaChannel{}
	var err error
	v.Channel, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.ReleaseID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Generation, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.PreviousReleaseID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.UpdatedAt, err = types.ReadTimestamp(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *AccountEmail) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.AccountID)
	w.PutString(v.Email)
}

func ReadAccountEmail(r bsatn.Reader) (*AccountEmail, error) {
	v := &AccountEmail{}
	var err error
	v.AccountID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Email, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *AccountBinding) WriteBsatn(w bsatn.Writer) {
	v.Sender.WriteBsatn(w)
	w.PutString(v.AccountID)
}

func ReadAccountBinding(r bsatn.Reader) (*AccountBinding, error) {
	v := &AccountBinding{}
	var err error
	v.Sender, err = types.ReadIdentity(r)
	if err != nil {
		return nil, err
	}
	v.AccountID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *AccountConnection) WriteBsatn(w bsatn.Writer) {
	v.Connection.WriteBsatn(w)
	v.Sender.WriteBsatn(w)
}

func ReadAccountConnection(r bsatn.Reader) (*AccountConnection, error) {
	v := &AccountConnection{}
	var err error
	v.Connection, err = types.ReadConnectionId(r)
	if err != nil {
		return nil, err
	}
	v.Sender, err = types.ReadIdentity(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *AccountDetails) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.ID)
	bsatn.WriteByteArray(w, v.PublicKey)
	w.PutU64(v.Revision)
	w.PutString(v.Email)
	w.PutString(v.DisplayName)
}

func ReadAccountDetails(r bsatn.Reader) (*AccountDetails, error) {
	v := &AccountDetails{}
	var err error
	v.ID, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.PublicKey, err = bsatn.ReadByteArray(r)
	if err != nil {
		return nil, err
	}
	v.Revision, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Email, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.DisplayName, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *OtaPublisher) WriteBsatn(w bsatn.Writer) {
	v.Identity.WriteBsatn(w)
}

func ReadOtaPublisher(r bsatn.Reader) (*OtaPublisher, error) {
	v := &OtaPublisher{}
	var err error
	v.Identity, err = types.ReadIdentity(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}
