// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/client"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// ModuleBindings ties together all table and view caches for the module.
type ModuleBindings struct {
	conn       client.DbConnection
	OtaRelease *OtaReleaseTable
	Account    *AccountTable
	OtaChannel *OtaChannelTable
	MyAccount  *MyAccountView
}

// NewModuleBindings registers all tables and views with the connection and
// returns a ModuleBindings with typed cache handles.
func NewModuleBindings(conn client.DbConnection) *ModuleBindings {
	c := conn.Cache()
	m := &ModuleBindings{conn: conn}
	m.OtaRelease = cache.RegisterTypedTableWithPK[*OtaRelease, string](c, otaReleaseTableDef{})
	m.Account = cache.RegisterTypedTableWithPK[*Account, string](c, accountTableDef{})
	m.OtaChannel = cache.RegisterTypedTableWithPK[*OtaChannel, string](c, otaChannelTableDef{})
	m.MyAccount = cache.RegisterTypedTable[*MyAccount](c, myAccountViewDef{})
	return m
}

// Conn returns the underlying database connection.
func (m *ModuleBindings) Conn() client.DbConnection {
	return m.conn
}
