// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"context"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type connectionPingArgs struct {
	Nonce uint64
}

func (a *connectionPingArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.Nonce)
}

// CallConnectionPing calls the connection_ping procedure on the server.
func CallConnectionPing(ctx context.Context, conn client.DbConnection, nonce uint64) (uint64, error) {
	var zero uint64
	args := &connectionPingArgs{
		Nonce: nonce,
	}
	raw, err := conn.CallProcedure(ctx, "connection_ping", args)
	if err != nil {
		return zero, err
	}
	result, err := readConnectionPingResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readConnectionPingResult(r bsatn.Reader) (*uint64, error) {
	var result uint64
	var err error
	result, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	_ = err
	return &result, nil
}
