// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type authorizeOtaPublisherArgs struct {
	Identity   string
	Authorized bool
}

func (a *authorizeOtaPublisherArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Identity)
	w.PutBool(a.Authorized)
}

// CallAuthorizeOtaPublisher calls the authorize_ota_publisher reducer on the server.
func CallAuthorizeOtaPublisher(conn client.DbConnection, identity string, authorized bool) error {
	args := &authorizeOtaPublisherArgs{
		Identity:   identity,
		Authorized: authorized,
	}
	return conn.CallReducer("authorize_ota_publisher", args)
}

type linkAccountArgs struct {
	Proof []byte
}

func (a *linkAccountArgs) WriteBsatn(w bsatn.Writer) {
	bsatn.WriteByteArray(w, a.Proof)
}

// CallLinkAccount calls the link_account reducer on the server.
func CallLinkAccount(conn client.DbConnection, proof []byte) error {
	args := &linkAccountArgs{
		Proof: proof,
	}
	return conn.CallReducer("link_account", args)
}

type promoteOtaChannelArgs struct {
	Channel            string
	ReleaseID          string
	ExpectedGeneration uint64
}

func (a *promoteOtaChannelArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Channel)
	w.PutString(a.ReleaseID)
	w.PutU64(a.ExpectedGeneration)
}

// CallPromoteOtaChannel calls the promote_ota_channel reducer on the server.
func CallPromoteOtaChannel(conn client.DbConnection, channel string, releaseID string, expectedGeneration uint64) error {
	args := &promoteOtaChannelArgs{
		Channel:            channel,
		ReleaseID:          releaseID,
		ExpectedGeneration: expectedGeneration,
	}
	return conn.CallReducer("promote_ota_channel", args)
}

type publishOtaReleaseArgs struct {
	ReleaseID      string
	ManifestJSON   string
	ManifestSha256 string
	ReleaseBaseURL string
}

func (a *publishOtaReleaseArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.ReleaseID)
	w.PutString(a.ManifestJSON)
	w.PutString(a.ManifestSha256)
	w.PutString(a.ReleaseBaseURL)
}

// CallPublishOtaRelease calls the publish_ota_release reducer on the server.
func CallPublishOtaRelease(conn client.DbConnection, releaseID string, manifestJSON string, manifestSha256 string, releaseBaseURL string) error {
	args := &publishOtaReleaseArgs{
		ReleaseID:      releaseID,
		ManifestJSON:   manifestJSON,
		ManifestSha256: manifestSha256,
		ReleaseBaseURL: releaseBaseURL,
	}
	return conn.CallReducer("publish_ota_release", args)
}

type registerAccountArgs struct {
	Proof []byte
}

func (a *registerAccountArgs) WriteBsatn(w bsatn.Writer) {
	bsatn.WriteByteArray(w, a.Proof)
}

// CallRegisterAccount calls the register_account reducer on the server.
func CallRegisterAccount(conn client.DbConnection, proof []byte) error {
	args := &registerAccountArgs{
		Proof: proof,
	}
	return conn.CallReducer("register_account", args)
}

type setAccountDisplayNameArgs struct {
	DisplayName string
	Proof       []byte
}

func (a *setAccountDisplayNameArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.DisplayName)
	bsatn.WriteByteArray(w, a.Proof)
}

// CallSetAccountDisplayName calls the set_account_display_name reducer on the server.
func CallSetAccountDisplayName(conn client.DbConnection, displayName string, proof []byte) error {
	args := &setAccountDisplayNameArgs{
		DisplayName: displayName,
		Proof:       proof,
	}
	return conn.CallReducer("set_account_display_name", args)
}

type setAccountEmailArgs struct {
	Email string
	Proof []byte
}

func (a *setAccountEmailArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Email)
	bsatn.WriteByteArray(w, a.Proof)
}

// CallSetAccountEmail calls the set_account_email reducer on the server.
func CallSetAccountEmail(conn client.DbConnection, email string, proof []byte) error {
	args := &setAccountEmailArgs{
		Email: email,
		Proof: proof,
	}
	return conn.CallReducer("set_account_email", args)
}
