// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// otaReleaseTableDef implements cache.TypedTableDef for the ota_release table.
type otaReleaseTableDef struct{}

func (otaReleaseTableDef) TableName() string { return "ota_release" }

func (otaReleaseTableDef) DecodeRow(r bsatn.Reader) (*OtaRelease, error) {
	return ReadOtaRelease(r)
}

func (otaReleaseTableDef) EncodeRow(row *OtaRelease) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (otaReleaseTableDef) PrimaryKey(row *OtaRelease) string {
	return row.ReleaseID
}

// OtaReleaseTable is a type-safe table cache for ota_release rows.
type OtaReleaseTable = cache.TypedTableCache[*OtaRelease]

// accountTableDef implements cache.TypedTableDef for the account table.
type accountTableDef struct{}

func (accountTableDef) TableName() string { return "account" }

func (accountTableDef) DecodeRow(r bsatn.Reader) (*Account, error) {
	return ReadAccount(r)
}

func (accountTableDef) EncodeRow(row *Account) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (accountTableDef) PrimaryKey(row *Account) string {
	return row.ID
}

// AccountTable is a type-safe table cache for account rows.
type AccountTable = cache.TypedTableCache[*Account]

// otaChannelTableDef implements cache.TypedTableDef for the ota_channel table.
type otaChannelTableDef struct{}

func (otaChannelTableDef) TableName() string { return "ota_channel" }

func (otaChannelTableDef) DecodeRow(r bsatn.Reader) (*OtaChannel, error) {
	return ReadOtaChannel(r)
}

func (otaChannelTableDef) EncodeRow(row *OtaChannel) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (otaChannelTableDef) PrimaryKey(row *OtaChannel) string {
	return row.Channel
}

// OtaChannelTable is a type-safe table cache for ota_channel rows.
type OtaChannelTable = cache.TypedTableCache[*OtaChannel]
