// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/types"
)

type Account struct {
	ID          string
	PublicKey   []byte
	Revision    uint64
	DisplayName string
}

type OtaRelease struct {
	ReleaseID      string
	ManifestJSON   string
	ManifestSha256 string
	ReleaseBaseURL string
	CreatedAt      types.Timestamp
}

type OtaAuthority struct {
	ID    uint8
	Owner types.Identity
}

type OtaChannel struct {
	Channel           string
	ReleaseID         string
	Generation        uint64
	PreviousReleaseID string
	UpdatedAt         types.Timestamp
}

type AccountEmail struct {
	AccountID string
	Email     string
}

type AccountBinding struct {
	Sender    types.Identity
	AccountID string
}

type AccountConnection struct {
	Connection types.ConnectionId
	Sender     types.Identity
}

type AccountDetails struct {
	ID          string
	PublicKey   []byte
	Revision    uint64
	Email       string
	DisplayName string
}

type OtaPublisher struct {
	Identity types.Identity
}
