// Code generated by stdb-go generate client; DO NOT EDIT.

package bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// myAccountViewDef implements cache.TypedTableDef for the my_account view.
type myAccountViewDef struct{}

func (myAccountViewDef) TableName() string { return "my_account" }

func (myAccountViewDef) DecodeRow(r bsatn.Reader) (*MyAccount, error) {
	return ReadMyAccount(r)
}

func (myAccountViewDef) EncodeRow(row *MyAccount) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// MyAccountView is a type-safe view cache for my_account rows.
type MyAccountView = cache.TypedTableCache[*MyAccount]
