// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channel: __t.string().primaryKey(),
  releaseId: __t.string().name("release_id"),
  generation: __t.u64(),
  previousReleaseId: __t.string().name("previous_release_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
