// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  releaseId: __t.string().primaryKey().name("release_id"),
  manifestJson: __t.string().name("manifest_json"),
  manifestSha256: __t.string().name("manifest_sha_256"),
  releaseBaseUrl: __t.string().name("release_base_url"),
  createdAt: __t.timestamp().name("created_at"),
});
