// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.string(),
  publicKey: __t.byteArray(),
  revision: __t.u64(),
  displayName: __t.string(),
});
export type Account = __Infer<typeof Account>;

export const AccountBinding = __t.object("AccountBinding", {
  sender: __t.identity(),
  accountId: __t.string(),
});
export type AccountBinding = __Infer<typeof AccountBinding>;

export const AccountConnection = __t.object("AccountConnection", {
  connection: __t.connectionId(),
  sender: __t.identity(),
});
export type AccountConnection = __Infer<typeof AccountConnection>;

export const AccountDetails = __t.object("AccountDetails", {
  id: __t.string(),
  publicKey: __t.byteArray(),
  revision: __t.u64(),
  email: __t.string(),
  displayName: __t.string(),
});
export type AccountDetails = __Infer<typeof AccountDetails>;

export const AccountEmail = __t.object("AccountEmail", {
  accountId: __t.string(),
  email: __t.string(),
});
export type AccountEmail = __Infer<typeof AccountEmail>;

export const OtaAuthority = __t.object("OtaAuthority", {
  id: __t.u8(),
  owner: __t.identity(),
});
export type OtaAuthority = __Infer<typeof OtaAuthority>;

export const OtaChannel = __t.object("OtaChannel", {
  channel: __t.string(),
  releaseId: __t.string(),
  generation: __t.u64(),
  previousReleaseId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type OtaChannel = __Infer<typeof OtaChannel>;

export const OtaPublisher = __t.object("OtaPublisher", {
  identity: __t.identity(),
});
export type OtaPublisher = __Infer<typeof OtaPublisher>;

export const OtaRelease = __t.object("OtaRelease", {
  releaseId: __t.string(),
  manifestJson: __t.string(),
  manifestSha256: __t.string(),
  releaseBaseUrl: __t.string(),
  createdAt: __t.timestamp(),
});
export type OtaRelease = __Infer<typeof OtaRelease>;

